# Generated by Django 6.0.7 on 2026-08-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('symbol_position', models.CharField(choices=[('prefix', 'prefix'), ('suffix', 'suffix')], default='prefix', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(default='Asia/Taipei', max_length=64)),
                ('search_engines', models.JSONField(default=list)),
                ('edu_email_suffix', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='core.currency')),
                ('default_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_regions', to='core.language')),
                ('languages', models.ManyToManyField(related_name='regions', to='core.language')),
            ],
        ),
    ]
