# Generated by Django 6.0.7 on 2026-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency_language_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['sort_order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['sort_order', 'code']},
        ),
    ]
