# Generated by Django 6.1.1 on 2026-10-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hong_kong_category_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.region')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['region', 'sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('region', 'code'), name='city_unique_code_per_region')],
            },
        ),
    ]
