# Generated by Django 6.0.7 on 2026-08-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_options_alter_language_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.region'),
        ),
    ]
