# Generated by Django 6.1.1 on 2026-09-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_convert_edu_email_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThrottleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('window_start', models.BigIntegerField(db_index=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'window_start'), name='one_throttle_counter_per_window')],
            },
        ),
    ]
