# Generated by Django 6.1.1 on 2026-10-08 03:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations

from core.migration_operations import AddPostgresIndex


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_notify_push'),
        ('catalog', '0003_book_upper_trgm_indexes'),
        ('core', '0006_seed_default_cities'),
        ('listings', '0003_listing_admin_lock_reason_listing_admin_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_course_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listing_professor_trgm_idx',
        ),
        AddPostgresIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('course_name'), name='gin_trgm_ops'), name='listing_course_upper_trgm_idx'),
        ),
        AddPostgresIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('professor_name'), name='gin_trgm_ops'), name='listing_prof_upper_trgm_idx'),
        ),
    ]
