# Generated by Django 6.0.7 on 2026-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_listing_course_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.JSONField(default=list, help_text='Array of full photo URLs (public URLs after R2 storage, see ListingUploadURLView)'),
        ),
    ]
