# Generated by Django 6.0.7 on 2026-08-21 15:58

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_school_email_domain_alter_user_avatar_url_and_more'),
        ('catalog', '0004_book_book_trgm_idx'),
        ('core', '0002_seed_categories'),
        ('listings', '0006_alter_listing_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='professor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['professor_name'], name='listing_professor_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
