# Generated by Django 6.0.7 on 2026-08-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_region_and_more'),
        ('listings', '0008_listing_currency_listing_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region'),
        ),
    ]
