# Generated by Django 6.0.7 on 2026-09-03 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_regionverification_edu_email'),
        ('catalog', '0007_alter_book_region'),
        ('core', '0010_convert_edu_email_suffix'),
        ('listings', '0010_backfill_listing_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['region', 'status', '-created_at'], name='listing_region_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['region', 'status', 'category'], name='listing_region_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['region', 'status', 'course_name'], name='listing_region_status_course_idx'),
        ),
    ]
