# Generated by Django 6.0.7 on 2026-08-19 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_school_email_domain_alter_user_avatar_url_and_more'),
        ('ads', '0002_advertiser_all_schools_advertiser_schools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(help_text='Advertiser it belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.advertiser'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='clicks_count',
            field=models.IntegerField(default=0, help_text='Click count statistics (update via F() expression only)'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='end_date',
            field=models.DateTimeField(help_text='End date'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(help_text='Ad banner image URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether it is active'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(choices=[('home_banner', 'Home Banner')], default='home_banner', help_text='Ad position', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start_date',
            field=models.DateTimeField(help_text='Start date'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='target_url',
            field=models.URLField(help_text='Target URL after click', max_length=500),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(help_text='Ad title, for internal identification', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views_count',
            field=models.IntegerField(default=0, help_text='View count statistics (update via F() expression only)'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='all_schools',
            field=models.BooleanField(default=True, help_text='Whether it applies to all schools'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='company_name',
            field=models.CharField(help_text='Company name', max_length=255),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='contact_email',
            field=models.EmailField(help_text='Contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether it is active'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='schools',
            field=models.ManyToManyField(blank=True, help_text='Specific schools it applies to', related_name='advertisers', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Reserved for future advertiser login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['is_active', 'position', 'start_date', 'end_date'], name='ad_active_pos_period_idx'),
        ),
    ]
