# Generated by Django 6.0.7 on 2026-08-20 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_advertiser_alter_ad_clicks_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='headline',
            field=models.CharField(blank=True, help_text='Headline', max_length=255),
        ),
        migrations.AddField(
            model_name='ad',
            name='slot_index',
            field=models.PositiveIntegerField(default=1, help_text='Display order (1-indexed, max 200)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='ad',
            name='subheadline',
            field=models.CharField(blank=True, help_text='Subheadline', max_length=255),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(help_text='建議 5:7 直式，最小 870x1218（供最大格 434x607 @2x 使用）', max_length=500),
        ),
    ]
