# Generated by Django 6.0.7 on 2026-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_headline_ad_slot_index_ad_subheadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(help_text='Recommended 5:7 portrait, min 870x1218 (for largest cell 434x607 @2x)', max_length=500),
        ),
    ]
