# Generated by Django 6.0.7 on 2026-08-20 16:32

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='labels',
            field=models.JSONField(blank=True, default=list, help_text='Custom labels (max 3, max 15 chars each)', validators=[ads.validators.validate_ad_labels]),
        ),
    ]
