# Generated by Django 6.0.7 on 2026-08-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='show_in_hero',
            field=models.BooleanField(default=False, help_text='Whether to display this ad as the first card in the home page hero cover stack'),
        ),
    ]
