# Generated by Django 6.0.7 on 2026-08-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ad_show_in_hero'),
        ('core', '0005_category_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='all_regions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='advertisers', to='core.region'),
        ),
    ]
