# Generated by Django 6.1.1 on 2026-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consolidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtokenrecord',
            name='family',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='refreshtokenrecord',
            index=models.Index(condition=models.Q(('rotated_at__isnull', True)), fields=['family'], name='refresh_token_live_by_family'),
        ),
    ]
