# Generated by Django 6.1.1 on 2026-10-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_avatar',
            field=models.BooleanField(default=True, help_text='Show the avatar to other users'),
        ),
    ]
