# Generated by Django 6.1.1 on 2026-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_show_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_region',
            field=models.CharField(blank=True, default='', help_text='Code of the verified region the user last used the site in, as reported by the frontend', max_length=2),
        ),
    ]
