# Generated by Django 6.0.7 on 2026-08-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_school_school_trgm_idx_user_user_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_domain',
            field=models.CharField(help_text='e.g.: ntu.edu.tw', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Avatar URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='edu_email',
            field=models.EmailField(blank=True, help_text='Verified campus email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Registration email, can be any email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_reverified_at',
            field=models.DateTimeField(blank=True, help_text='Time of last student identity re-verification', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Time of first successful .edu.tw verification', null=True),
        ),
    ]
