# Generated by Django 6.0.7 on 2026-08-27 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_school_email_domain_alter_user_avatar_url_and_more'),
        ('core', '0005_category_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='core.region'),
        ),
        migrations.CreateModel(
            name='RegionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_email', models.EmailField(max_length=254, unique=True, null=True, blank=True)),
                ('is_manual_verification', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_reverified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='core.region')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='accounts.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'region'), name='one_verification_per_user_region')],
            },
        ),
    ]
