# Generated by Django 6.0.7 on 2026-08-27 13:36

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_school_region_user_managed_regions_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_alter_category_region_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_trgm_idx',
        ),
        migrations.AlterField(
            model_name='regionverification',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='core.region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='core.region'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['email', 'first_name', 'last_name'], name='user_trgm_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops']),
        ),
        migrations.RemoveField(
            model_name='user',
            name='edu_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_reverified_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_at',
        ),
    ]
