# Generated by Django 6.0.7 on 2026-08-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_user_trgm_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionverification',
            name='edu_email',
            field=models.EmailField(blank=True, help_text='Null for manual verifications.', max_length=254, null=True, unique=True),
        ),
    ]
