# Generated by Django 6.0.7 on 2026-09-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_new_message_email',
            field=models.BooleanField(default=True, help_text='Email the user about a chat message that arrives while they are not on the site'),
        ),
    ]
