# Generated by Django 6.0.7 on 2026-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_notify_new_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_language',
            field=models.CharField(default='auto', help_text="Language for notification emails: 'auto' (follow site_language), or zh-TW / zh-HK / en", max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='site_language',
            field=models.CharField(blank=True, default='', help_text='The language the user last used the site in, as reported by the frontend', max_length=10),
        ),
    ]
