# Generated by Django 6.0.7 on 2026-09-18 09:57

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_school_code_required_unique_per_region'),
        ('core', '0010_convert_edu_email_suffix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_website', models.URLField(max_length=500)),
                ('edu_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('added', 'Added'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_requests', to='core.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['region', 'status', '-created_at'], name='schoolreq_region_status_idx')],
                'constraints': [models.UniqueConstraint(models.F('user'), models.F('region'), django.db.models.functions.text.Lower('school_name'), condition=models.Q(('status', 'pending')), name='one_pending_school_request_per_user_region_name')],
            },
        ),
    ]
