# Generated by Django 6.1.1 on 2026-09-23 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_school_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenRecord',
            fields=[
                ('jti', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_tokens', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('rotated_at__isnull', True)), fields=['user'], name='refresh_token_live_by_user')],
            },
        ),
    ]
