# Generated by Django 6.1.1 on 2026-09-24 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_refresh_token_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('register', 'Registration'), ('edu_verify', 'Campus email verification'), ('password_reset', 'Password reset'), ('email_change', 'Email change')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose'], name='one_time_token_user_purpose')],
            },
        ),
    ]
