# Generated by Django 6.0.7 on 2026-08-27 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_user_trgm_idx_and_more'),
        ('catalog', '0007_alter_book_region'),
        ('core', '0007_alter_category_region_and_more'),
        ('subscriptions', '0002_subscription_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'region'], name='subscriptio_user_id_f45386_idx'),
        ),
    ]
