# Generated by Django 6.1.1 on 2026-10-08 03:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations

from core.migration_operations import AddPostgresIndex


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_review'),
        ('core', '0006_seed_default_cities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_trgm_idx',
        ),
        AddPostgresIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='book_title_upper_trgm_idx'),
        ),
        AddPostgresIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('authors'), name='gin_trgm_ops'), name='book_authors_upper_trgm_idx'),
        ),
        AddPostgresIndex(
            model_name='book',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('isbn13'), name='gin_trgm_ops'), name='book_isbn13_upper_trgm_idx'),
        ),
    ]
