# Generated by Django 6.0.7 on 2026-08-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_book_trgm_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('listed', 'Listed'), ('preseed', 'Preseed'), ('manual', 'Manual'), ('google_api', 'Google Books API'), ('openlibrary_api', 'Open Library API'), ('isbnnet_api', 'ISBNnet API')], max_length=20),
        ),
    ]
