# Generated by Django 6.0.7 on 2026-08-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_source'),
        ('core', '0005_category_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.region'),
        ),
    ]
