# Generated by Django 6.0.7 on 2026-08-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_region'),
        ('core', '0007_alter_category_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.region'),
        ),
    ]
