# Generated by Django 6.1.1 on 2026-09-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_clear_guessed_openlibrary_covers'),
        ('core', '0011_throttle_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('region', 'isbn13'), name='book_region_isbn13_uniq'),
        ),
    ]
