# Generated by Django 6.1.1 on 2026-10-01 01:02

import django.db.models.deletion
from django.db import migrations, models


def backfill_listing_snapshot(apps, schema_editor):
    """Copy each row's listing details while the listing still exists — see
    listings/snapshot.py. Rows created from now on fill it in save()."""
    from django.db.models import F, OuterRef, Subquery, Value
    from django.db.models.functions import Coalesce

    Model = apps.get_model('orders', 'Order')
    Listing = apps.get_model('listings', 'Listing')
    listing = Listing.objects.filter(pk=OuterRef('listing_id'))
    Model.objects.filter(listing__isnull=False, listing_ref__isnull=True).update(
        listing_ref=F('listing_id'),
        book_title=Coalesce(Subquery(listing.values('book__title')[:1]), Value('')),
        book_isbn=Coalesce(Subquery(listing.values('book__isbn13')[:1]), Value('')),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_admin_lock_reason_listing_admin_locked_and_more'),
        ('orders', '0001_consolidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='book_isbn',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AddField(
            model_name='order',
            name='book_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='listing_ref',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='listings.listing'),
        ),
        migrations.RunPython(backfill_listing_snapshot, migrations.RunPython.noop),
    ]
