# Generated by Django 6.0.7 on 2026-09-17 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_convert_edu_email_suffix'),
        ('listings', '0011_listing_feed_indexes'),
        ('orders', '0008_alter_order_currency_alter_order_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['region', 'created_at'], name='order_region_created_idx'),
        ),
    ]
