# Generated by Django 6.0.7 on 2026-09-21 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_convert_edu_email_suffix'),
        ('listings', '0011_listing_feed_indexes'),
        ('orders', '0010_completed_and_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meetup_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the meetup reminder was fully sent', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when meetup reminder was sent to buyer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when meetup reminder was sent to seller', null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'meetup_time'], name='order_status_meetup_time_idx'),
        ),
    ]
