# Generated by Django 6.0.7 on 2026-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_meetup_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when meetup reminder was sent to buyer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when meetup reminder was sent to seller', null=True),
        ),
    ]
